name: TurtleJoin
main: io.github.turtley12.TurtleJoin.Main
version: 1.0
author: Turtley12
api-version: 1.16

commands:
  turtlejoin:
    description: Main TurtleJoin Command
    permission: turtlejoin.admin
    
permissions:
  turtlejoin.admin:
    description: Access for TurtleJoin admin commands
    